Jwt security
mkazarian-1/Book-Shop pull request #11
Opened 2024-10-09 14:21 UTC by mkazarian-1

2024-10-09 14:46 UTC, Elena-Bruyako requested changes
see comments

2024-10-09 14:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/security/JwtAuthorizationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-10-09 14:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/security/JwtAuthorizationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
create constant for "Bearer "

2024-10-09 14:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/security/JwtAuthorizationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(constant.length());
```

2024-10-10 11:34 UTC, Elena-Bruyako requested changes
one comment

2024-10-10 11:34 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/config/SecurityConfig.java
> +                        .permitAll()
combine into one requestMatchers

2024-10-11 08:43 UTC, ahoienko approved these changes
Good job! Please check minor comment

2024-10-11 08:43 UTC, ahoienko commented on src/main/java/org/example/bookshop/dto/user/UserLoginRequestDto.java
> +    @Pattern(regexp = "^[^@]+@[^@]+\\.[^@]+$")
```suggestion
    @NotBlank
    @Email
```

2024-10-11 13:53 UTC, merged