Order implementation
mkazarian-1/Book-Shop pull request #14
Opened 2024-11-04 23:00 UTC by mkazarian-1

2024-11-05 08:39 UTC, Elena-Bruyako requested changes
see comments

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/controller/OrderController.java
> +    public List<OrderDto> getOrderHistory(@PageableDefault(size = 5) Pageable pageable) {
it's better to return Page instead of List

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/controller/OrderController.java
> +        User user = UserUtil.getCurrenSesstionUser();
rename method or suggestion - return userId from this method

```suggestion
        User user = UserUtil.getAuthenticatedUser();
```

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/Order.java
> +    private LocalDateTime orderDate;
Suggestion, you can initialize date
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/Order.java
> +    private Status status;
Suggestion 
```suggestion
    private Status status = Status.NEW;
```

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/repository/CartItemRepository.java
> +    @Transactional
```suggestion
```

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/OrderServiceImpl.java
> +    @Override
Check where `@Transactional` is required

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/OrderServiceImpl.java
> +        return orderItemMapper.toDto(orderItemRepository
let's make it more readable, create local variable OrderItem

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/OrderServiceImpl.java
> +        return orderItemMapper.toDtoList(orderRepository.findByIdAndUserId(orderId, userId)
let's make it more readable, create local variable Order

2024-11-05 08:39 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/OrderServiceImpl.java
> +
check if shoppingCart.getCartItems().isEmpty()

2024-11-06 18:35 UTC, Elena-Bruyako requested changes
see comments

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/BookServiceImpl.java
> +    @Transactional
```suggestion
```

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CategoryServiceImpl.java
> +    @Transactional
```suggestion
```

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CategoryServiceImpl.java
> +    @Transactional
```suggestion
```

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CategoryServiceImpl.java
> +    @Transactional
```suggestion
```

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/OrderServiceImpl.java
> +            throw new EntityNotFoundException("Can't create order by empty cart. UserId:"
```suggestion
            throw new OrderProcessingException("Can't create order by empty cart. UserId:"
```

2024-11-06 18:35 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-11-06 21:05 UTC, mkazarian-1 commented
Do I understand correctly that we don't need to use @Transactional when we have only one change method like save, delete, etc?

2024-11-07 15:45 UTC, Elena-Bruyako approved these changes

2024-11-23 12:02 UTC, merged