Search books
mkazarian-1/Book-Shop pull request #6
Opened 2024-09-18 17:03 UTC by mkazarian-1

2024-09-18 17:51 UTC, okuzan requested changes

2024-09-18 17:51 UTC, okuzan commented on src/main/java/org/example/bookshop/repository/book/IsbnSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("isbn")
use constant for a repeated literal in providers

2024-09-18 17:51 UTC, okuzan commented on src/main/java/org/example/bookshop/repository/SpecificationProviderManagerImpl.java
> +                    "There is no SpecificationProvider with this key" + key));
use provider instead of short naming b
use NoSuchElementException or create a custom exception

2024-09-19 08:26 UTC, sarakhmen approved these changes

2024-09-19 08:26 UTC, sarakhmen commented on src/main/java/org/example/bookshop/repository/BookSpecificationBuilder.java
> +
```suggestion
```

2024-09-19 08:26 UTC, sarakhmen commented on src/main/java/org/example/bookshop/repository/SpecificationProviderManagerImpl.java
> +
```suggestion
```

2024-09-19 08:26 UTC, sarakhmen commented on src/main/java/org/example/bookshop/repository/book/TitleSpecificationProvider.java
> +
```suggestion
```

2024-09-19 19:44 UTC, merged